default_language_version:
    python: python3.10

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files


  - repo: https://github.com/PyCQA/autoflake
    rev: v2.0.2
    hooks:
      - id: autoflake
        args: [--in-place, --remove-all-unused-imports, --remove-duplicate-keys]
        exclude: venv/

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args: [--line-length=119, --target-version=py37]
        exclude: venv/

  - repo: 'https://gitlab.com/pycqa/flake8'
    rev: 3.8.2
    hooks:
        - id: flake8
        additional_dependencies:
          - flake8-bugbear
  - repo: local
    hooks:
      - id: tests
        name: Run tests
        entry: "bash run_tests.sh"
        language: system
        verbose: true
