name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8', '3.9', '3.10'
          architecture: 'x64'
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: flake8
        run: python -m flake8 --max-line-length=119 --ignore=E128,F401 core/*.py

      - name: Tests
        run: pytest -v